### ISSUE TITLE
Improvement: Exclude ODBC Tables

### ISSUE THREAD

**Issue by thr27** [spannm/ucanaccess#10]
We have a lot of ODBC based Tables in our access databases. 

ucanaccess is unable to load the access database because it fails to load these with the following error:

**UCAExc:::5.1.0 TableDefinition has no data access (Db=Test1.accdb; Table=some_odbc_table_name**

As ucanaccess will probably never be able to import ODBC based tables, it should exclude ODBC tables from the list of tables.

I would propose ... function createTables in **src\main\java\net\ucanaccess\converters\LoadJet.java** should check if table is ODBC_LINK and not add them to the list.

Line: 1070 ...

```
                if (t2 != null && t != null && !tn.startsWith("~")) {
                    
                    TableMetaData tableMetaData = t2.getDatabase().getTableMetaData(tn);
                    if (tableMetaData.getType() == TableMetaData.Type.LINKED_ODBC) {
                        logger.log(Level.WARNING, "Table {0} is linked to an ODBC table. Skipped ...", tn);
                        unresolvedTables.add(tn);
                    }else{
                        createTable(t);
                        loadingOrder.add(t.getName());
                    }
                }
...
```

**Comment by spannm** [comment]
Hi @thr27!
Thanks for raising this issue. Your suggestion sounds quite reasonable. I will look into it shortly
Markus

**Comment by spannm** [comment]
Hi @thr27, incorporated you suggestion. Please review

**Comment by thr27** [comment]
Thank you
