### ISSUE TITLE
Docs: minor updates

### ISSUE THREAD

**Issue by gordthompson** [spannm/ucanaccess#17]
A couple of minor issues with https://spannm.github.io/ucanaccess/10-index.html

- The top bar has a "GitHub Wiki" link but the wiki has not been enabled.

- The top bar also says "Version: 5.1.1-SNAPSHOT" but we now have an official release of 5.1.2. :heart: 

- The "Dependencies" section says _"If you are manually managing your classpath, you will need to add the ucanaccess-5.1.0.jar file along with its dependencies to your classpath."_ Some mention of the Uber jar would be helpful there.

**Comment by spannm** [comment]
Thanks for pointing this out.
The Maven site requires updating - will do soon.

**Comment by gordthompson** [comment]
Overall, the docs are still in fairly decent shape, IMO. If I notice any more specific changes I can submit a PR for the .xhtml file(s).

Thanks.
