### ISSUE TITLE
Read HSQLDB mirror from elsewhere

### ISSUE THREAD

**Issue by RivenSkaye** [spannm/ucanaccess#18]
I'm using this project to get some DB insights and views working from an IDE, but for some reason I'm getting a generated `PUBLIC` database, and any select query being ran against it gets generated with the DB prefix, which makes the IDE error out. So I figured I'd open the HSQLDB separately as a readonly mirror instead, but I'm not able to find what name was given to the HSQLDB mirror

**Comment by spannm** [comment]
By default the HSQLDB backing database is in memory.
Set the `keepMirror` driver property to specify a path where a persistent copy of the backing database files should be stored. Setting this property implies `memory=false`.

**Comment by RivenSkaye** [comment]
I have that set - the issue is that subsequently using the HSQLDB driver for my IDE's DB explorer is asking for a database name. I've tried a lot of things, but can't seem to get anything that works to open the database

**Comment by spannm** [comment]
I don't have any good advice for you I'm afraid, as the issue isn't really clear.

Try another tool such as [DbVisualizer](https://www.dbvis.com/)?

The db's `.script` and `.properties` files are plain text. Can you locate and open them in a text editor?

**Comment by RivenSkaye** [comment]
The .script isn't exactly that plain, thanks to encrypted in == encrypted out.
And the properties file isn't supplying me with a name to target:
```ini
#HSQL Database Engine 2.5.0
#Fri Nov 22 14:39:12 UTC 2024
modified=no
tx_timestamp=0
version=2.5.0
```

screenshot of the .script file; forcing other encodings gives me incorrect Chinese text w/ mojibake at best
![image](https://github.com/user-attachments/assets/baf4f9ba-24ab-4f74-b68c-c5fc00d9347c)

**Comment by RivenSkaye** [comment]
Okay, so rebuilding the HSQLDB and then opening it with DBVisualizer seems to be a magic trick - it now opens from my IDE as well. I subsequently get a lock error from the HSQLDB JDBC driver in my IDE, but closing DBVisualizer and reloading the IDE connection seems to do the trick. It's weird, but now it does finally recognize the name `PUBLIC` for the DB

**Comment by RivenSkaye** [comment]
Okay, after some more tinkering I've made it work on the HSQLDB file end -- what's going wrong now seems to be on Rider's end so I'll open a bug report there. (Unexpected identifier that does not even exist in the connection string)
