### ISSUE TITLE
jquery version in doc\website\htdocs is vulnerable

### ISSUE THREAD

**Issue by kingca31** [spannm/ucanaccess#2]
Hi everybody,
thanks to all to maintaining this project alive.

Should it be possible to update jquery-3.2.1.min.js embedded in doc\website\htdocs\ to a less-vulnerable and more recent version?
It shouldn't be heavily impacting.

Thanks and Best Regards,
M.

**Comment by spannm** [comment]
Hello kingca31,
thanks for feedback! As suggested I've switched to the most recent jQuery. Also updated contents of `site.html`
Many regards & happy holidays
Markus

**Comment by kingca31** [comment]
Hello @spannm ,
thank you for your prompt feedback and correction.

BR,
kingca

**Comment by kingca31** [comment]
hello @spannm,
I was wondering if there will also be another release of ucanaccess containing these changes.
The last version published in 5.1.0.

Thanks!

BR,
kingca

**Comment by spannm** [comment]
Reopening

**Comment by spannm** [comment]
Hello @kingca31,

hope this finds you well!
I've removed the documentation from the jar altogether and instead publish it as a Maven site under [this url](https://spannm.github.io/ucanaccess/).

The next release with these changes will be done soon.

cheers
Markus

**Comment by kingca31** [comment]
Hi @spannm , thank you for the nice news.

BR,
Michael

**Comment by spannm** [comment]
UCanAccess Release v5.1.1 is on its way
