### ISSUE TITLE
Update is not working.

### ISSUE THREAD

**Issue by pizzadox9999** [spannm/ucanaccess#20]
Hi, i am at the end of my competence. I tried to create an update statement and execute it in a normal fashion but i get the exeption of:

net.ucanaccess.exception.UcanaccessSQLException: UCAExc:::5.1.2 user lacks privilege or object not found: UPDATE in statement [UPDATE orders SET order_date = ?, product_name = ?, cost_center = ?, sap_number_id = ?, banf = ?, order_number = ?, supplier = ?, article_number = ?, amount = ?, requestor_de_number_id = ?, expected_delivery_date = ?, orderer_de_number_id = ?, comment = ? WHERE id_order = ? AND UPDATE orders SET order_date = ?, product_name = ?, cost_center = ?, sap_number_id = ?, banf = ?, order_number = ?, supplier = ?, article_number = ?, amount = ?, requestor_de_number_id = ?, expected_delivery_date = ?, orderer_de_number_id = ?, comment = ? WHERE id_order = ?;]. 

The ddl for the table is:

database.execute("CREATE TABLE orders ("
				+ "id_order AUTOINCREMENT NOT NULL,"
				+ "order_date LONG NOT NULL,"
				+ "product_name TEXT NOT NULL,"
				+ "cost_center TEXT NOT NULL,"
				+ "sap_number_id LONG NOT NULL,"
				+ "banf TEXT NOT NULL,"
				+ "order_number TEXT NOT NULL,"
				+ "supplier TEXT NOT NULL,"
				+ "article_number TEXT NOT NULL,"
				+ "amount DOUBLE NOT NULL,"
				+ "requestor_de_number_id TEXT NOT NULL,"
				+ "expected_delivery_date LONG,"
				+ "orderer_de_number_id TEXT NOT NULL,"
				+ "comment TEXT,"
				+ "PRIMARY KEY(id_order)"
				+ ");");
which also works quite nice.

The record seem to exist before i try to execute to the statements. I am using java 11 with at least to my knowleadge most recent version of the database driver. Insert and select statement seem to work regardless.

I develop with the eclipse ide
Version: 2022-12 (4.26.0)
Build id: 20221201-1913 on

I controll my depencys with the ingetrated version of maven (should be 2 or something)

Edition Windows 11 Enterprise
Version	23H2
build	22631.4460
Windows Feature Experience Pack 1000.22700.1047.0

If somebody needs any further information please let me know.
Thanks guys for any help.

Best regards pizzadox999

**Comment by gordthompson** [comment]
The error message shows that you are trying to execute the following SQL (reformatted for clarity):

```sql
UPDATE orders SET order_date = ?, product_name = ?, cost_center = ?, sap_number_id = ?, banf = ?, order_number = ?, supplier = ?, article_number = ?, amount = ?, requestor_de_number_id = ?, expected_delivery_date = ?, orderer_de_number_id = ?, comment = ? WHERE id_order = ? 
AND 
UPDATE orders SET order_date = ?, product_name = ?, cost_center = ?, sap_number_id = ?, banf = ?, order_number = ?, supplier = ?, article_number = ?, amount = ?, requestor_de_number_id = ?, expected_delivery_date = ?, orderer_de_number_id = ?, comment = ? WHERE id_order = ?;
```

which is invalid syntax. (That's not what `AND` is used for.) Are you trying to update multiple rows by executing a single SQL string?

**Comment by pizzadox9999** [comment]
Sorry for the late reply. Thank you very much for your help. It was a dark day, which you brought light in. Best regards pizzadox9999.
