### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by sualeh** [spannm/ucanaccess#4]
Enable the Discussions tab on this GitHub project for public discussions.

**Comment by spannm** [comment]
Discussions enabled

**Comment by gordthompson** [comment]
I'm not seeing it:

![uca](https://github.com/spannm/ucanaccess/assets/15894006/4929eb41-2f8a-4993-9042-f3c082b11b26)

**Comment by spannm** [comment]
I had the discussion feature enabled for a while (with no usage), then disabled it again.
I am not convinced of its usefulness and also a little afraid that it creates a support burdon.

**Comment by gordthompson** [comment]
As you wish. I looked for it because I was going to let you know that I wrote a few posts for

http://ucanaccess.blogspot.com/

and you're welcome to incorporate some or all of them into your docs, or put them in your wiki here if you decide to enable it.

**Comment by spannm** [comment]
Your contributions are most welcome, Gord (@gordthompson)
Discussions are now enabled and will stay enabled. Thanks for your feedback!
