### ISSUE TITLE
Possible ConcurrentModificationException while making a connection

### ISSUE THREAD

**Issue by sualeh** [spannm/ucanaccess#5]
Please see the [ConcurrentModificationException stack trace in this failure](https://github.com/schemacrawler/SchemaCrawler/actions/runs/7434311119/job/20228327113) (you will need to scroll up). This is with the old driver, but it may still be an issue. I do not have a test case to reproduce at this point, since it is an intermittent failure.

**Comment by spannm** [comment]
Hi @sualeh,

The stacktrace you're referring to:
```
2024-01-06T22:41:33.8586728Z Caused by: java.util.ConcurrentModificationException
2024-01-06T22:41:33.8587768Z 	at java.util.Hashtable$Enumerator.next(Hashtable.java:1408)
2024-01-06T22:41:33.8589089Z 	at net.ucanaccess.jdbc.UcanaccessDriver.readProperties(UcanaccessDriver.java:300)
2024-01-06T22:41:33.8590536Z 	at net.ucanaccess.jdbc.UcanaccessDriver.connect(UcanaccessDriver.java:68)
```
The `ConcurrentModificationException` occurs while the driver loops over (reads) driver property entries. (I am assuming your project uses v5.0.1)
https://sourceforge.net/p/ucanaccess/git-code/ci/master/tree/src/main/java/net/ucanaccess/jdbc/UcanaccessDriver.java#l300
The Properties object is therefore modified in another thread elsewhere. Please check the code calling the driver, in particular `org.apache.commons.dbcp2.DriverConnectionFactory` and method `getProperties()` which gives public access to the Properties object.

The new driver handles driver properties somewhat differently, but still needs to loop over the entries. Thus it can suffer from the same issue.

**Comment by sualeh** [comment]
I could not find a smoking gun, so I am closing the issue for now.
